### ISSUE TITLE
Exporting COBie for Curtain Walls

### ISSUE THREAD

**Issue by michelecarradori** [opensourceBIM/COBie-plugins#10]
Hi everyone,
I am a student in Building Engineering and I am delivering my thesis mainly on the delivery of COBie data for a company involved in the field of curtain walls and building envelope. I am trying to export COBie from an Ifc file through BIMserver using the COBie plugin, but I have some problems with IfcPlate and IfcMember (tipically associated to panels and mullions); in general with all the Ifc entities which are not included in the spreadsheet by BIMserver.
I tried to explore the COBie plugin and I discovered there are some .xml files (like COBieIgnore or COBieIgnorePlusProxyObjects, for example) in which the Ifc entities ignored by BIMserver are listed. I modified these files, erasing the entities I want to export, but I know that is not enough. Could you help me? How can I export panels and mullions, defined in the Ifc file as IfcPlate and IfcMember, in COBie?
(I saw that these entities appears in the Document worksheet, but not in the Type and Component ones, why does it happen?)
Thank you for the time you will spend helping me!

**Comment by OhmSweetOhm** [comment]
Hi,

Per the Facility Management Handover MVD specification, those IfcPlate and IfcMember entities are excluded from COBie exports.  A few versions ago the COBie plugins relied on the BIMServer IDM plugins to filter most of the non-relevant entities from the export: actually, an IDM plugin filters what is loaded from the model and handed to the serializer code.  Anyway, the IDM plugin functionality appears to be broken in BIMServer 1.4.  Those ignore.xml files are leftovers from the days when the IDM plugins worked.  And back in those days we had several IDM plugins so that folks (such as yourself) could load other non FM Handover entities into a spreadsheet export.  

In the current version of the code, the filtering of entities occurs in the COBie export code - specifically, it is the code that transforms IFC entities into COBie Type and Component.  Those IfcPlate and IfcMember entities should not appear in Document and you have caught a bug - THANKS!  

Unfortunately, none of that helps you at the moment.  If you are tech savvy enough to download the code, modify it, and run BIMServer in Eclipse then I can tell you how you can change it so that it will export those elements.  Otherwise, in the future, one of the things I would like to do is to provide the list of ignored entities as a BIMServer setting (accessible to the user via the admin interface.  

But for sure, we need to fix that IfcPlate and IfcMember Document tab issue sooner than later.

I'll keep you posted on any developments.

Thanks

**Comment by michelecarradori** [comment]
Thank you for you answer,
I found yesterday the "COBie toolkit", which is, as you probably know, a BIMserver-based tool that allows me to export COBie data without running BIMserver. Maybe it is the old version of the COBie plugin you were talking about (or something similar), because I can load different IDMplugin filters and get the entities I need, IfcPlate and IfcMember included.

**Comment by OhmSweetOhm** [comment]
No problem. The COBie Toolkit runs the COBie IFC conversions and COBie checking code independent of BIMServer.  We originally developed that application for the COBie Challenge events so that the vendors had a tool to check their models.  The COBie specific code in the Toolkit was the same as the COBie Plugin code at that time - whenever the last version of the Toolkit was pushed (a year ago maybe?).  

You are correct though, the IDM functionality should work in that Toolkit.

Regards

Chris

**Comment by OhmSweetOhm** [comment]
Good news.  There is now support for this in  [Release1.1.4](https://github.com/opensourceBIM/COBie-plugins/releases/tag/1.1.4)

It will require a little bit of editing of the COBie export config file in the BIMServer home\CobiePlugins\config folder.  If you know anything about XML then simply comment out or delete the lines in the config file that refer to IfcCurtainWallType and IfcCurtainWall.
