### ISSUE TITLE
"dummy" attributes not being filtered correctly

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#24]
There is a list of dummy attributes such as "pen weight" and "line color" that should always be eliminated from any IFC export of COBie. Current testing of an IFC file has demonstrated that these properties are not being eliminated. see the attached example file. (https://github.com/opensourceBIM/COBie-plugins/files/226089/EDORM-CDL-00-ZZ-M3-E-1001.IFC.Electrical.model.-.COBie.US2.zip)

here are sample plotting instructions:
#196503= IFCPROPERTYSINGLEVALUE('Type',$,IFCLABEL('Level: 8mm Head'),$);
#196504= IFCPROPERTYSINGLEVALUE('Type Id',$,IFCLABEL('Level: 8mm Head'),$);
#196505= IFCPROPERTYSINGLEVALUE('Elevation Base',$,IFCIDENTIFIER('Project Base Point'),$);
#196506= IFCPROPERTYSINGLEVALUE('Color',$,IFCINTEGER(0),$);
#196507= IFCPROPERTYSINGLEVALUE('Line Pattern',$,IFCLABEL('Centre'),$);
#196508= IFCPROPERTYSINGLEVALUE('Line Weight',$,IFCIDENTIFIER('1'),$);
#196509= IFCPROPERTYSINGLEVALUE('Symbol',$,IFCLABEL('Level Head - Circle: Level Head - Circle'),$);
#196510= IFCPROPERTYSINGLEVALUE('Symbol at End 1 Default',$,IFCBOOLEAN(.F.),$);
#196511= IFCPROPERTYSINGLEVALUE('Symbol at End 2 Default',$,IFCBOOLEAN(.T.),$);
#196512= IFCPROPERTYSINGLEVALUE('Type Name',$,IFCTEXT('8mm Head'),$);
#196513= IFCPROPERTYSINGLEVALUE('Family Name',$,IFCTEXT('Level'),$);
#196514= IFCPROPERTYSET('3Zu5Bv0LOHrPC11XI6FoQQ',#47,'Constraints',$,(#196496));
#196516= IFCRELDEFINESBYPROPERTIES('3Zu5Bv0LOHrPC11nI6FoQQ',#47,$,$,(#128),#196514);
#196519= IFCPROPERTYSET('3Zu5Bv0LOHrPC11ao6FoQQ',#47,'Data',$,(#449,#196489,#196490,#196491,#196492,#196493,#196494,#196495));

there are also a lot of properties directly named for COBie that are often duplicated in the correct IFC data as well. an example of such properties include:
#196489= IFCPROPERTYSINGLEVALUE('COBie.CreatedBy',$,IFCTEXT('Daniel@cadandesign.com'),$);
#196490= IFCPROPERTYSINGLEVALUE('COBie.CreatedOn',$,IFCTEXT('2016-03-31T09:38:31'),$);
#196491= IFCPROPERTYSINGLEVALUE('COBie.Floor.Category',$,IFCTEXT('Floor'),$);
#196492= IFCPROPERTYSINGLEVALUE('COBie.Floor.Description',$,IFCTEXT('Level One'),$);
#196493= IFCPROPERTYSINGLEVALUE('COBie.Floor.Elevation',$,IFCLENGTHMEASURE(100000.),$);
#196494= IFCPROPERTYSINGLEVALUE('COBie.Floor.Height',$,IFCLENGTHMEASURE(0.),$);
#196495= IFCPROPERTYSINGLEVALUE('COBie.Floor.Name',$,IFCTEXT('Level One'),$);

[EDORM-CDL-00-ZZ-M3-E-1001 IFC Electrical model - COBie US2.zip]

**Comment by OhmSweetOhm** [comment]
Resolution of this issue is in progress.  As a reminder to myself about how this currently works, here are some technicals:

Currently, these sorts of things are filtered out via some hard-coded lists that were built years ago.  The original intent was that eventually, these would be off-loaded to an external configuration file or options settings.  

The org.bimserver.cobie.shared.serialization.util.IfcToAttribute class contains the list of attribute names that should be ignored.  These lists are evaluated according to the type of the parent object (e.g. Ignore  Type attributes with these names, Ignore Component attributes with these names...).

Here is a snippet of code that contains the list of attribute names:

  protected static ArrayList<String> facilityExclusions = new ArrayList<String>(Arrays.asList("Phase"));
    protected static ArrayList<String> floorExclusions = new ArrayList<String>(Arrays.asList("Elevation"));
    protected static ArrayList<String> spacePropertySetNameExclusions = new ArrayList<String>(Arrays.asList("BaseQuantities"));
    protected static ArrayList<String> spaceExclusions = new ArrayList<String>(Arrays.asList("GrossArea", "NetArea", "UsableHeight", "FloorName",
            " Area", "Number", "ZoneName"));
    protected static ArrayList<String> typeExclusions = new ArrayList<String>(Arrays.asList("AssetType", "IsFixed", "Manufacturer", "ModelNumber",
            "ModelLabel", "WarrantyGuarantorParts", "WarrantyDurationParts", "WarrantyGuarantorLabor", "WarrantyDurationLabor",
            "WarrantyDurationUnit", "ReplacementCost", "Cost", "LifeCyclePhase", "ExpectedLife", "ServiceLifeDuration", "ServiceLifeType",
            "DurationUnit", "WarrantyDescription", "WarrantyName", "NominalLength", "NominalWidth", "NominalHeight", "ModelReference", "Shape",
            "Size", "Color", "Finish", "Grade", "Material", "Constituents", "Features", "AccessibilityPerformance", "CodePerformance",
            "SustainabilityPerformance"));
    protected static ArrayList<String> componentExclusions = new ArrayList<String>(Arrays.asList("SerialNumber", "InstallationDate",
            "WarrantyStartDate", "TagNumber", "BarCode", "AssetIdentifier", "System Name", "System Type", "Circuit Number"));
    protected static ArrayList<String> allExclusions = new ArrayList<String>(Arrays.asList("Category", "MethodOfMeasurement", "Omniclass Number",
            "Omniclass Title", "Assembly Code", "Assembly Description", "Uniclass Code", "Uniclass Description", "Category Code",
            "Category Description", "Classification Code", "Classification Description", "Name", "Description", " AssetAccountingType ",
            " GSA BIM Area ", "Half Oval ", " Height ", " Length ", "Hot Water Radius", "Host", "Level ", " Size ",
            " Lighting Calculation Workplan ", "Limit Offset", "Recepticles", "Mark", " Offset ", " Omniclass ", "Outside Diameter ",
            "Outside Radius ", "Phase", "Phase Created", " Radius ", "Window Inset", "Width ", "Symbol", "Line Pattern", "Roomtag", "Upper Limit",
            "Base Offset", " Zone "));

**Comment by OhmSweetOhm** [comment]
Also, note, some attribute names contain spaces at the beginning and/or end.  This was a quick and dirty way for me to encode comparison types:
-If the list item begins and ends with a space then a "contains" comparison is made.  E.g. exclude any attribute that contains "Raidus" (case insensitive)

-If the list item begins with a space but does not end with a space then an "ends with" comparison should is made.  I'm not sure if there are any in the lists that meet this criteria

-If the list item ends with a space but does not begin with a space then a "starts with" comparison is made, e.g. Ignore all attributes that begin with "Outside Diameter" (case insensitive)

-If the list item does not begin or end with a space then an exact comparison should be made, e.g., ignore attributes with name equal to "Classification Description" (case insensitive)  

As stated, this is a nasty way to do this and it should be refactored to use an XML file so that these things are more explicit and tailorable.

**Comment by OhmSweetOhm** [comment]
Fixed in [Release1.1.4](https://github.com/opensourceBIM/COBie-plugins/releases/tag/1.1.4), commit d8739ce
