### ISSUE TITLE
All Tabs.CreatedOn Error

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#32]
All CreatedOn dates are exporting as seconds from 1900 (or whatever) versus either the date on the ifcOwnerHistory object or the date that the file was exported "2017-01-04T10:45:00"

[ARC.xlsx](https://github.com/opensourceBIM/COBie-plugins/files/687766/ARC.xlsx)

**Comment by OhmSweetOhm** [comment]
There was a change in the last update regarding how the date values are written to the spreadsheet file.  In the latest version the dates are populated in the Excel spreadsheet file as date values.  The formatting of those columns will determine how the date is actually displayed.  The spreadsheet templates (blank) currently have those formatted as General.  Will either have to change the code to write those dates as text values or change all date columns in the blank template to be formatted as dates.  I'd prefer the latter because it makes the data in the spreadsheets better - and would allow you to sort by date columns.

**Comment by OhmSweetOhm** [comment]
Fixed in release 1.1.6 and Commit ade5ae606327888230510906c7d35b3620d251e1
